### ISSUE TITLE
get-nf-balance API returns all nf token for addresses with 0 balance

### ISSUE THREAD

**Issue by PaulBernier** [Factom-Asset-Tokens/fatd#9]
If get-nf-balance is called for an address that doesn't own any NF token the method return ALL the NF tokens in circulation. If the address own some NF tokens then it returns the correct result.

**Comment by PaulBernier** [comment]
I think it may be a bit more complicated than the case I mentioned above, here's another inconsistent result I get:

```bash
paul@paul-XPS-13-9370:~/factom/fatd/fat-cli$ curl -X POST --data-binary '{"jsonrpc": "2.0", "id": 0, "method":"get-nf-balance", "params": {"chainid":"8ce27193600dd3051b4d394b2d7f2d2e83d10c4d2fe470631d46f34852a90905", "address":"FA2V4Bk8Gm2LpJciLKvXCxqL4AeHbCwu3GyhFyb6HeBiqibRhMYu"}}' -H 'content-type:text/plain;' http://localhost:8078/v1
{"jsonrpc":"2.0","result":[],"id":0}
paul@paul-XPS-13-9370:~/factom/fatd/fat-cli$ curl -X POST --data-binary '{"jsonrpc": "2.0", "id": 0, "method":"get-balance", "params": {"chainid":"8ce27193600dd3051b4d394b2d7f2d2e83d10c4d2fe470631d46f34852a90905", "address":"FA2V4Bk8Gm2LpJciLKvXCxqL4AeHbCwu3GyhFyb6HeBiqibRhMYu"}}' -H 'content-type:text/plain;' http://localhost:8078/v1
{"jsonrpc":"2.0","result":3,"id":0}
```
The call to `get-balance` returns "3" but the call to `get-nf-balance` returns empty list.

**Comment by AdamSLevy** [comment]
@PaulBernier Please let me know if you are still experiencing this bug.

**Comment by PaulBernier** [comment]
I'm getting this error now:
```
jsonrpc2: panic running method (jsonrpc2.MethodFunc)(0x80c7d0): MethodFunc error: json: error calling MarshalJSON for type fat1.NFTokens: fat1.NFTokens: empty
goroutine 52 [running]:
github.com/AdamSLevy/jsonrpc2/v10.MethodFunc.call.func1(0xc0007ff810, 0x9cb210, 0xc0005ec000, 0x8f, 0x90, 0xc0007ff710)
	/home/paul/go/pkg/mod/github.com/!adam!s!levy/jsonrpc2/v10@v10.0.0/methods.go:63 +0xf8
panic(0x901480, 0xc000068e00)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/AdamSLevy/jsonrpc2/v10.MethodFunc.call(0x9cb210, 0xc0005ec000, 0x8f, 0x90, 0x0, 0x0, 0x0, 0x0, 0xf90fc0, 0x0, ...)
	/home/paul/go/pkg/mod/github.com/!adam!s!levy/jsonrpc2/v10@v10.0.0/methods.go:104 +0x55c
github.com/AdamSLevy/jsonrpc2/v10.processRequest(0xc0001f27e0, 0xc00064a000, 0xce, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/paul/go/pkg/mod/github.com/!adam!s!levy/jsonrpc2/v10@v10.0.0/handler.go:114 +0x362
github.com/AdamSLevy/jsonrpc2/v10.handle(0xc0001f27e0, 0xc00020db00, 0x6aa703, 0xc0004a41a5)
	/home/paul/go/pkg/mod/github.com/!adam!s!levy/jsonrpc2/v10@v10.0.0/handler.go:65 +0x278
github.com/AdamSLevy/jsonrpc2/v10.HTTPRequestHandler.func1(0xa33640, 0xc0000de000, 0xc00020db00)
	/home/paul/go/pkg/mod/github.com/!adam!s!levy/jsonrpc2/v10@v10.0.0/handler.go:17 +0x49
net/http.HandlerFunc.ServeHTTP(0xc000208190, 0xa33640, 0xc0000de000, 0xc00020db00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0001f2b40, 0xa33640, 0xc0000de000, 0xc00020db00)
	/usr/local/go/src/net/http/server.go:2361 +0x127
github.com/rs/cors.(*Cors).Handler.func1(0xa33640, 0xc0000de000, 0xc00020db00)
	/home/paul/go/pkg/mod/github.com/rs/cors@v1.3.0/cors.go:200 +0xf2
net/http.HandlerFunc.ServeHTTP(0xc0001b63c0, 0xa33640, 0xc0000de000, 0xc00020db00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
net/http.serverHandler.ServeHTTP(0xf91d00, 0xa33640, 0xc0000de000, 0xc00020db00)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc000174500, 0xa33980, 0xc00020a380)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
jsonrpc2: Params: {"chainid":"8ce27193600dd3051b4d394b2d7f2d2e83d10c4d2fe470631d46f34852a90905","address":"FA2V4Bk8Gm2LpJciLKvXCxqL4AeHbCwu3GyhFyb6HeBiqibRhMYu"}
jsonrpc2: Return: fat1.NFTokens{}
Method: "get-nf-balance"
```

**Comment by AdamSLevy** [comment]
Ah that's right. I deliberately designed the type to prevent marshaling
empty nftoken sets. I will add a check for it being empty.

**Comment by PaulBernier** [comment]
I don't know if I'm doing anything wrong but I still have issues:

```bash
jsonrpc2: panic running method (jsonrpc2.MethodFunc)(0x80c7d0): runtime error: invalid memory address or nil pointer dereference
goroutine 95 [running]:
github.com/AdamSLevy/jsonrpc2/v10.MethodFunc.call.func1(0xc0008cf810, 0x9cb2f0, 0xc0000f0fc0, 0x8f, 0x90, 0xc0008cf710)
	/home/paul/go/pkg/mod/github.com/!adam!s!levy/jsonrpc2/v10@v10.0.0/methods.go:63 +0xf8
panic(0x92b600, 0xf4d080)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/gocraft/dbr.(*Connection).NewSession(...)
	/home/paul/go/pkg/mod/github.com/!adam!s!levy/dbr@v0.0.0-20190204220409-06403a96499f/dbr.go:73
github.com/Factom-Asset-Tokens/fatd/state.Chain.GetNFTokensForOwner(0xc000520820, 0x3, 0xc000520900, 0xc000715000, 0x3, 0x0, 0xed3bf1be8, 0xf91960, 0x1, 0x2710, ...)
	/home/paul/factom/fatd/state/db.go:358 +0x42
github.com/Factom-Asset-Tokens/fatd/srv.getNFBalance(0xc0000f0fc0, 0x8f, 0x90, 0x9cb2f0, 0xc0000f0fc0)
	/home/paul/factom/fatd/srv/methods.go:215 +0x21a
github.com/AdamSLevy/jsonrpc2/v10.MethodFunc.call(0x9cb2f0, 0xc0000f0fc0, 0x8f, 0x90, 0x0, 0x0, 0x0, 0x0, 0xf90fc0, 0x0, ...)
	/home/paul/go/pkg/mod/github.com/!adam!s!levy/jsonrpc2/v10@v10.0.0/methods.go:70 +0xfc
github.com/AdamSLevy/jsonrpc2/v10.processRequest(0xc0002007e0, 0xc000514a00, 0xce, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/paul/go/pkg/mod/github.com/!adam!s!levy/jsonrpc2/v10@v10.0.0/handler.go:114 +0x362
github.com/AdamSLevy/jsonrpc2/v10.handle(0xc0002007e0, 0xc000492d00, 0x6aa703, 0xc000494de5)
	/home/paul/go/pkg/mod/github.com/!adam!s!levy/jsonrpc2/v10@v10.0.0/handler.go:65 +0x278
github.com/AdamSLevy/jsonrpc2/v10.HTTPRequestHandler.func1(0xa33740, 0xc0007747e0, 0xc000492d00)
	/home/paul/go/pkg/mod/github.com/!adam!s!levy/jsonrpc2/v10@v10.0.0/handler.go:17 +0x49
net/http.HandlerFunc.ServeHTTP(0xc0004faff0, 0xa33740, 0xc0007747e0, 0xc000492d00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0001c23c0, 0xa33740, 0xc0007747e0, 0xc000492d00)
	/usr/local/go/src/net/http/server.go:2361 +0x127
github.com/rs/cors.(*Cors).Handler.func1(0xa33740, 0xc0007747e0, 0xc000492d00)
	/home/paul/go/pkg/mod/github.com/rs/cors@v1.3.0/cors.go:200 +0xf2
net/http.HandlerFunc.ServeHTTP(0xc00020ee80, 0xa33740, 0xc0007747e0, 0xc000492d00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
net/http.serverHandler.ServeHTTP(0xf91d00, 0xa33740, 0xc0007747e0, 0xc000492d00)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0000a77c0, 0xa33a80, 0xc000550040)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
jsonrpc2: Params: {"chainid":"f265e7fe26ce81d5f8fdd021735b3783f7c3f49883cb58d6b0d25568467c0193","address":"FA26EeEaqatCkEvQ5k3uy2cDVVRhAmoA9F6VdFGQKoPcgT3j47CF"}
jsonrpc2: Return: <nil>
Method: "get-nf-balance"
```

**Comment by PaulBernier** [comment]
And still have this problem of `get-balance` vs `get-nf-balance`:

```bash
paul@paul-XPS-13-9370:~/factom/fatd/fat-cli$ curl -X POST --data-binary '{"jsonrpc": "2.0", "id": 0, "method":"get-balance", "params": {"chainid":"f265e7fe26ce81d5f8fdd021735b3783f7c3f49883cb58d6b0d25568467c0193", "address":"FA2D1Jmno3hwKQDMfcv5J9CdVDB9eXz2KhS7TvrP3usZfXmUkM6u"}}' -H 'content-type:text/plain;' http://localhost:8078/v1
{"jsonrpc":"2.0","result":1,"id":0}
paul@paul-XPS-13-9370:~/factom/fatd/fat-cli$ curl -X POST --data-binary '{"jsonrpc": "2.0", "id": 0, "method":"get-nf-balance", "params": {"chainid":"f265e7fe26ce81d5f8fdd021735b3783f7c3f49883cb58d6b0d25568467c0193", "address":"FA2D1Jmno3hwKQDMfcv5J9CdVDB9eXz2KhS7TvrP3usZfXmUkM6u"}}' -H 'content-type:text/plain;' http://localhost:8078/v1
{"jsonrpc":"2.0","result":[],"id":0}
```
The address holds 1 token but the get-nf-token returns empty array. Here's the whole chain of that FAT-1 token:

![image](https://user-images.githubusercontent.com/5141652/52553717-65fbc580-2e49-11e9-9a85-9707cc433944.png)

**Comment by AdamSLevy** [comment]
@PaulBernier can you please use a sqlite browser to examine the database? Or send me the database for that chain.

I want to know if the balance column in the addresses table agrees with the ownership described by the nf_tokens table data.

**Comment by AdamSLevy** [comment]
So the balance discrepancy is a separate issue from the original issue and issues stemming from its fix. If you can reproduce it when rebuilding the database for that chain then I would like it to be opened in a separate issue.

Regarding the latest panic you experienced, I cannot reproduce this with my build. I am requesting an address that is not in the database which for me returns an empty array. Similarly requesting an address that is in the database but has a zero balance works as expected.

**Comment by PaulBernier** [comment]
I confirm both the panic issue and the nf-balance issue have been fixed. Thanks!
